apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: random-db
  labels:
    app: postgresql
    component: secret
    lab: lab2
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change_me" 

