apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-storage
  namespace: random-db
  labels:
    app: postgresql
    component: backup
    lab: lab2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd-expandable
  resources:
    requests:
      storage: 50Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: random-db
  labels:
    app: postgresql
    component: backup
    lab: lab2
spec:
  schedule: "0 2 * * *"  # Tous les jours à 2h du matin
  successfulJobsHistoryLimit: 7  # Conserver 7 jours de backups
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: postgresql
            component: backup
        spec:
          containers:
          - name: postgres-backup
            image: postgres:15-alpine
            command:
              - /bin/sh
              - -c
              - |
                set -e
                BACKUP_DIR="/backups/$(date +%Y%m%d)"
                mkdir -p "$BACKUP_DIR"
                
                # Créer le dump
                echo "Création du backup PostgreSQL..."
                PGPASSWORD="$POSTGRES_PASSWORD" pg_dump \
                  -h postgres.random-db.svc.cluster.local \
                  -U "$POSTGRES_USER" \
                  -d "$POSTGRES_DB" \
                  -F c \
                  -f "$BACKUP_DIR/postgres_backup.dump"
                
                # Compresser le dump
                gzip "$BACKUP_DIR/postgres_backup.dump"
                
                # Nettoyer les backups de plus de 7 jours
                find /backups -type d -mtime +7 -exec rm -rf {} + 2>/dev/null || true
                
                echo "Backup terminé: $BACKUP_DIR/postgres_backup.dump.gz"
                ls -lh "$BACKUP_DIR/"
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            volumeMounts:
            - name: backup-storage
              mountPath: /backups
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: postgres-backup-storage
          restartPolicy: OnFailure

