---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd-expandable
  resources:
    requests:
      storage: 50Gi

