---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
stringData:
  root-user: minioadmin
  root-password: minioadmin123!
  # En production, utiliser un secret généré aléatoirement
  # root-password: $(openssl rand -base64 32)

