---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
  labels:
    app: monitoring
    component: logs
    env: production
  annotations:
    description: "Loki log aggregation system"
    contact: "platform-team@random.com"

