---
apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-credentials
  namespace: loki
type: Opaque
stringData:
  access-key-id: minioadmin
  secret-access-key: minioadmin123!
  # En production, utiliser les mêmes credentials que MinIO mais depuis un secret externe

