---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-logs-config
  namespace: alloy-logs
data:
  config.yaml: |
    logging:
      level: info
      format: logfmt

    loki.source.kubernetes "k8s_logs" {
      targets = discovery.kubernetes.pods.targets
      forward_to = [loki.write.loki.receiver]
    }

    discovery.kubernetes "pods" {
      role = "pod"
      selectors {
        role = "pod"
      }
      relabel "namespace" {
        target_label = "namespace"
        source_labels = ["__meta_kubernetes_namespace"]
      }
      relabel "pod_name" {
        target_label = "pod_name"
        source_labels = ["__meta_kubernetes_pod_name"]
      }
      relabel "container_name" {
        target_label = "container_name"
        source_labels = ["__meta_kubernetes_pod_container_name"]
      }
      relabel "node_name" {
        target_label = "node_name"
        source_labels = ["__meta_kubernetes_pod_node_name"]
      }
    }

    loki.write "loki" {
      endpoint {
        url = "http://loki-gateway.loki.svc.cluster.local:80"
      }
      external_labels = {
        source = "alloy-logs"
      }
    }

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy-logs
  namespace: alloy-logs
  labels:
    app: alloy-logs
spec:
  selector:
    matchLabels:
      app: alloy-logs
  template:
    metadata:
      labels:
        app: alloy-logs
    spec:
      serviceAccountName: alloy-logs
      containers:
      - name: alloy
        image: grafana/alloy:latest
        args:
          - run
          - /etc/alloy/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/alloy
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: alloy-logs-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-logs
  namespace: alloy-logs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-logs
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-logs
subjects:
- kind: ServiceAccount
  name: alloy-logs
  namespace: alloy-logs

