---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local:80
        jsonData:
          maxLines: 1000
        editable: true
      
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir-gateway.mimir.svc.cluster.local:80/prometheus
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          httpHeaderValue1: "pods"
        editable: true
      
      - name: Mimir-Nodes
        type: prometheus
        access: proxy
        url: http://mimir-gateway.mimir.svc.cluster.local:80/prometheus
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          httpHeaderValue1: "nodes"
        editable: true
      
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-query-frontend.tempo.svc.cluster.local:3200
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: loki
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            mapTagNamesEnabled: false
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: false
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: mimir
            tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
            queries:
              - name: 'Sample query'
                query: 'sum(rate(tempo_spanmetrics_latency_bucket{$$__tags}[5m]))'
          serviceMap:
            datasourceUid: mimir
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: loki
        editable: true

