---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app: monitoring
    component: infrastructure
    env: production
  annotations:
    description: "Infrastructure monitoring components"
    contact: "platform-team@random.com"

